# These are supported funding model platforms

github: [Proxima84-code]        # Twój GitHub Sponsors (włącz, jeśli chcesz)
patreon: proxima84              # Twój profil Patreon
open_collective:                
ko_fi: proxima84                # Twój profil Ko-fi
tidelift:                       
community_bridge:               
liberapay: proxima84            # Twój profil Liberapay
issuehunt:                      
lfx_crowdfunding:               
polar:                          
buy_me_a_coffee: proxima84      # Twój profil Buy Me a Coffee
thanks_dev:                     
custom: ['https://payhip.com/proxima84', 'https://twojastrona.com/wsparcie']
